spring.application.name=sms-backend
# Database connection settings
spring.datasource.url=jdbc:postgresql://localhost:5432/sms_db
spring.datasource.username=sms
spring.datasource.password=password

# Hibernate settings (This is the "Magic" part)
# 'update' means Hibernate will automatically create the tables
# for your @Entity classes when you start the app.
spring.jpa.hibernate.ddl-auto=update

# Show SQL in the console so you can see what JPA is doing
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect